name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: '2.2.106'
  CONFIGURATION: 'Release'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: dotnet restore, build, test and publish
      run: |
           dotnet restore
           dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore
           dotnet test --no-restore --configuration  ${{ env.CONFIGURATION }} --collect "Code coverage" --filter "TestCategory!=UI"
           dotnet publish './src/Web/Web.csproj' --no-restore --configuration ${{ env.CONFIGURATION }} --output 'web.zip'
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
       name: Web
       path: 'web.zip'   
